name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # get repo code
      - uses: actions/checkout@v2
      # Install node
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      # run checksum check
      - run: yarn --frozen-lockfile
      - run: yarn checksum